services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - recommender-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    depends_on:
      - postgres
    networks:
      - recommender-net
    entrypoint: bash -c "airflow db init && \
                         airflow users create --username admin --password admin \
                         --firstname Admin --lastname User --role Admin --email admin@example.com"
  
  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=bahMfW5PxSWQlXK4FmRPqy62fhZBGV97x75rZBIEW8g=
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    networks:
      - recommender-net
    command: bash -c "airflow webserver"

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    depends_on:
      - postgres
      - airflow-init
    networks:
      - recommender-net
    command: bash -c "airflow scheduler"

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_DB=recommendation
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    ports:
      - "8123:8123"  # HTTP port
      - "9000:9000"  # TCP port
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - recommender-net

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    working_dir: /app
    environment:
      - CLICKHOUSE_HOST=172.18.0.3
      - CLICKHOUSE_PORT=9000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./fastapi:/app
    ports:
      - "8000:8000"
    networks:
      - recommender-net
    depends_on:
      - clickhouse-server

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: streamlit
    working_dir: /app
    volumes:
      - ./streamlit:/app
    ports:
      - "8501:8501"
    networks:
      - recommender-net
    depends_on:
      - fastapi

networks:
  recommender-net:
    name: recommender-net

volumes:
  postgres-data:
  clickhouse-data:
      